### PR TITLE
Updated to use Packer 1.5 APIs and some other fixes

### PR DESCRIPTION
**Pull request by darkedges**
Updated to use Packer 1.5 APIs and some other fixes including
- OS Based Temp firectory
- cleaned up execute_command handling

May be a multi os solution for https://github.com/mefellows/packer-dsc/issues/3

### CODE REVIEW

**Comment by darkedges** [comment]
I can create a version without the vendor files if that helps, IIRC go 1.13 will automatically get them based on `vendor.yml` if `vendors` does not exist, but it seems most projects now include `vendors` by default nowadays.

**Comment by mefellows** [comment]
Thanks so much, this is great! Somebody actually pinged me about this today and I made the changes...without looking here. But yours look much more exhaustive (except tests will need updating).

As for vendoring - yes, I think we should probably move to Go modules (if not straight to `PROXY`, but I'm inclined to wait a little). 

I'll need a few days to pull this all together and ensure the integration tests (manual) pass. 

Locally mine works, so I might push up and then iterate from there.

**Comment by mefellows** [comment]
For some confidence, this was my branch working against an AWS account I have.

Screen Shot 2020-02-11 at 2 43 45 pm

**Comment by darkedges** [comment]
Sorry for lateness.
I was pinged too hence why I made the updates to my fork.
Most of the additional changes were around getting the plugin working on Windows and the temp file location etc. 

I think the vendor issue masks the changes within github.

Glad to see it working, I assumed mine would too as it was just some API changes.

**Comment by niknabo** [comment]
Hi, I am new to Packer, DSC, and Go and I'm having a little trouble trying to figure out how I can use nirving's version with the fixed API in a Windows environment. Is it possible to have the master branch here updated with these fixes and a new binary created for 64-bit Windows? Or, could someone please expand on how I can use a local library and Go to get this working?

**Comment by mefellows** [comment]
Hi @niknabo, apologies - it looks like the tests are broken so the release process didn't run. I've manually released the latest artifacts - hope it helps!

I haven't been able to look at this project for a while, as I'm too busy with my [other](https://pact.io) [children](https://pactflow.io). I'll try keep an eye out here though to see how you get on :)

**Comment by niknabo** [comment]
> Hi @niknabo, apologies - it looks like the tests are broken so the release process didn't run. I've manually released the latest artifacts - hope it helps!
> 
> I haven't been able to look at this project for a while, as I'm too busy with my [other](https://pact.io) [children](https://pactflow.io). I'll try keep an eye out here though to see how you get on :)

Thank you! I was able to successfully use dsc as a provisioner with the latest version (1.7) of packer!

Edit: Whoops, jumped the gun a bit. I am still getting the API warning with version 1.7 of Packer, but it _is_ working with version 1.66

**Comment by mefellows** [comment]
🎉

**Pull request merged**
